name: Main Workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Verify data type definitions

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip3 install pydsdl

      - name: Run data types verification script
        run: ./verify
